### ISSUE TITLE
Iceman mannequin effect

### ISSUE THREAD

**Issue by ak2yny** [ak2yny/OpenHeroSelectGUI#1]
Add a cold effect for Iceman (and others), similar to Human Torch's effect.
[Suggested by Rampage](https://discord.com/channels/449510825385000960/450488661461565441/1059958602342866966).
I'm adding this here, because I want to add the effects function from the Stage & Herostat Helper eventually. Doing this with HeroSelect (or even my helper) is so much easier than doing it manually.
![image](https://user-images.githubusercontent.com/92672223/216338227-9742e826-7c04-4eda-bd13-382c6c5557aa.png)

**Comment by JordanLeich** [comment]
Will this ever be an optional for the ocp? Just curious.

**Comment by ak2yny** [comment]
Yes. I will not make this effect until the GUI has the functionality included, but someone else can do it. There is a tutorial on marvelmods.com about how to make mannequin effects manually.

**Comment by ak2yny** [comment]
I tested it and we can maximum have two effects at the same time. ~~The GUI will have the option to add effects to each location, but these can't be disabled in the F12 menu.~~

_Edit: The crash (see below) happens when adding more than two effects. I was able to add a third because of another bug. It's still possible to add more effects and it might come in the future, but they will never be hidden in the F12 menu._

**Comment by ak2yny** [comment]
![Marvel_ Ultimate Alliance 2023-07-17 12_07_19 PM](https://github.com/ak2yny/OpenHeroSelectGUI/assets/92672223/72df5c62-e4e5-432f-b950-6bdb6e884aa9)
![Marvel_ Ultimate Alliance 2023-07-17 12_07_20 PM](https://github.com/ak2yny/OpenHeroSelectGUI/assets/92672223/1c4aa060-9833-45c1-91be-7450bbe53c6a)
